#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (C) 2026 Samuele Voltan
#
# The three bricks a stick figure is made of, and the grass it stands on.
#
#   python tools/gen_bricks.py examples/poc14-kickoff/assets
#
# Every previous example baked one model of one thing: a ship is a ship. A
# football team is eighty-eight parts that are all the same three shapes at
# different sizes, so what gets baked here is not a player — it is a box, a
# sphere and a wedge, each one unit-sized, and the player is arithmetic.
#
# That is why the three share a vertex layout down to the byte (position,
# normal, uv, stride 32): one compiled shader draws all of them, and the only
# thing that differs between a head and a shin is the matrix in front of it.
#
# Conventions match the rest of Crema: Y up, -Z forward, faces CCW seen from
# outside. Each brick fits the unit cube so that the numbers in the game read
# as metres — a 0.46 x 0.62 x 0.26 torso is a torso, not a scale factor.

import math
import os
import sys

# --- OBJ writing -------------------------------------------------------------
#
# Faces carry explicit normals rather than letting the baker infer them,
# because two of these three want flat shading and one does not: a cube with
# smoothed corners is a bad cube, and a faceted ball is a bad ball.


class Obj:
    def __init__(self, name):
        self.name = name
        self.verts = []     # (x, y, z)
        self.uvs = []       # (u, v)
        self.norms = []     # (x, y, z)
        self.faces = []     # [(vi, ti, ni), ...] 1-based, as OBJ wants

    def vertex(self, p, uv, n):
        self.verts.append(p)
        self.uvs.append(uv)
        self.norms.append(n)
        return len(self.verts)

    def tri(self, a, b, c):
        self.faces.append((a, b, c))

    def write(self, path):
        lines = ["# Crema brick - generated by tools/gen_bricks.py, MIT",
                 "o " + self.name]
        for p in self.verts:
            lines.append("v %.6f %.6f %.6f" % p)
        for t in self.uvs:
            lines.append("vt %.6f %.6f" % t)
        for n in self.norms:
            lines.append("vn %.6f %.6f %.6f" % n)
        for f in self.faces:
            lines.append("f " + " ".join("%d/%d/%d" % (i, i, i) for i in f))
        with open(path, "w", encoding="utf-8") as fh:
            fh.write("\n".join(lines) + "\n")
        return len(self.faces), len(self.verts)


def normal(a, b, c):
    ux, uy, uz = b[0] - a[0], b[1] - a[1], b[2] - a[2]
    vx, vy, vz = c[0] - a[0], c[1] - a[1], c[2] - a[2]
    n = (uy * vz - uz * vy, uz * vx - ux * vz, ux * vy - uy * vx)
    length = math.sqrt(sum(k * k for k in n))
    if length < 1e-9:
        return None
    return (n[0] / length, n[1] / length, n[2] / length)


def flat_tri(obj, a, b, c, uva, uvb, uvc):
    """One triangle with one normal for all three corners: the face is flat and
    says so, which is what makes a cube read as a cube."""
    n = normal(a, b, c)
    if n is None:
        return
    ia = obj.vertex(a, uva, n)
    ib = obj.vertex(b, uvb, n)
    ic = obj.vertex(c, uvc, n)
    obj.tri(ia, ib, ic)


def flat_quad(obj, a, b, c, d):
    """A face of a box, UV-mapped 0..1 over the quad. Nothing samples it today
    — the bricks are lit tints, not textures — but a layout that differs
    between meshes is a second shader, and the point of these three is that
    there is only one."""
    flat_tri(obj, a, b, c, (0, 0), (1, 0), (1, 1))
    flat_tri(obj, a, c, d, (0, 0), (1, 1), (0, 1))


# --- the box -----------------------------------------------------------------
#
# Torso, upper arms, thighs, goalposts, and the bar across the top of them.
# Centred on its own origin, one metre on a side, so a scale is a size.

def build_box():
    o = Obj("box")
    h = 0.5
    # corners, named by sign: (x, y, z)
    p = {}
    for sx in (-1, 1):
        for sy in (-1, 1):
            for sz in (-1, 1):
                p[(sx, sy, sz)] = (sx * h, sy * h, sz * h)

    # Each quad wound CCW seen from outside the cube.
    flat_quad(o, p[(-1, -1, 1)], p[(1, -1, 1)], p[(1, 1, 1)], p[(-1, 1, 1)])    # +Z
    flat_quad(o, p[(1, -1, -1)], p[(-1, -1, -1)], p[(-1, 1, -1)], p[(1, 1, -1)])  # -Z
    flat_quad(o, p[(1, -1, 1)], p[(1, -1, -1)], p[(1, 1, -1)], p[(1, 1, 1)])    # +X
    flat_quad(o, p[(-1, -1, -1)], p[(-1, -1, 1)], p[(-1, 1, 1)], p[(-1, 1, -1)])  # -X
    flat_quad(o, p[(-1, 1, 1)], p[(1, 1, 1)], p[(1, 1, -1)], p[(-1, 1, -1)])    # +Y
    flat_quad(o, p[(-1, -1, -1)], p[(1, -1, -1)], p[(1, -1, 1)], p[(-1, -1, 1)])  # -Y
    return o


# --- the sphere --------------------------------------------------------------
#
# Head, hands, and the ball — which is the reason this one is smooth-shaded and
# properly UV-mapped while the other two are neither. A head could be faceted
# and nobody would mind; a ball that spins has to show that it is spinning, and
# the only thing carrying that information is the texture coordinate.

def build_sphere(meridians=16, parallels=12):
    o = Obj("sphere")
    r = 0.5

    def point(i, j):
        u = i / meridians
        v = j / parallels
        lon = u * 2.0 * math.pi
        lat = v * math.pi                      # 0 = north pole
        sx = math.sin(lat) * math.sin(lon)
        sy = math.cos(lat)
        sz = math.sin(lat) * math.cos(lon)
        pos = (sx * r, sy * r, sz * r)
        nrm = (sx, sy, sz)                     # unit sphere: position IS normal
        return pos, (u, 1.0 - v), nrm

    def add(i, j):
        pos, uv, nrm = point(i, j)
        return o.vertex(pos, uv, nrm)

    for j in range(parallels):
        for i in range(meridians):
            a = add(i, j)
            b = add(i, j + 1)
            c = add(i + 1, j + 1)
            d = add(i + 1, j)
            # The pole rows collapse to a point on one side; emitting the
            # degenerate triangle anyway would leave a zero-area face in the
            # buffer, so skip it — the baker's closure check counts edges.
            if j > 0:
                o.tri(a, b, d)
            if j < parallels - 1:
                o.tri(b, c, d)
    return o


# --- the wedge ---------------------------------------------------------------
#
# A foot. Spheres were considered and rejected for the obvious reason: a ball
# on the end of a leg cannot tell you which way a player is facing, and in a
# game where the whole point is which way somebody is about to kick, the foot
# is the arrow.
#
# Four vertices: a flat sole, a toe at -Z (forward), and the ankle sitting back
# and up, where a leg can meet it.

def build_wedge():
    o = Obj("wedge")
    toe = (0.0, 0.0, -0.5)
    heel_l = (-0.5, 0.0, 0.5)
    heel_r = (0.5, 0.0, 0.5)
    ankle = (0.0, 1.0, 0.30)

    flat_tri(o, toe, heel_r, heel_l, (0.5, 0.0), (1, 1), (0, 1))     # sole, -Y
    flat_tri(o, toe, heel_l, ankle, (0.5, 0.0), (0, 1), (0.5, 1))    # left
    flat_tri(o, toe, ankle, heel_r, (0.5, 0.0), (0.5, 1), (1, 1))    # right
    flat_tri(o, heel_l, heel_r, ankle, (0, 0), (1, 0), (0.5, 1))     # back
    return o


# --- the grass ---------------------------------------------------------------
#
# A pitch is not a green rectangle, and the reason is the mower: it lays the
# blades one way going up and the other way coming back, and the light catches
# the two directions differently. That is the entire trick, and it is why a
# real pitch on television reads as a surface with a size rather than a flat
# fill — the stripes give the eye something to measure distance against.
#
# The texture tiles over the pitch, so the stripe period is the tile period:
# one light band and one dark band per tile, and the game picks how many metres
# a tile is worth. The white lines are NOT in here — they are geometry, because
# a line baked into a tiling texture would repeat, and a line drawn on a
# non-tiling one would be a blurry smear the moment the camera came close.

def write_grass(path, size=256):
    from PIL import Image

    img = Image.new("RGBA", (size, size))
    px = img.load()

    for y in range(size):
        for x in range(size):
            # Two mowing bands across the tile, with a soft edge — a mower does
            # not leave a hard line, and a hard line here would alias into a
            # crawling seam as the camera pans.
            band = math.sin(2.0 * math.pi * x / size)
            mow = 0.5 + 0.5 * math.tanh(band * 4.0)

            # Deterministic grain, no seed to remember: a hash of the position
            # that repeats with the tile, so the wrap is seamless by
            # construction rather than by blurring the edges.
            h = (x * 374761393 + y * 668265263) & 0xFFFFFFFF
            h = (h ^ (h >> 13)) * 1274126177 & 0xFFFFFFFF
            grain = ((h >> 16) & 0xFF) / 255.0 - 0.5

            # Blade streaks along the mowing direction: short vertical strokes
            # that survive minification into a texture that is not flat.
            streak = math.sin((x * 5 + ((h >> 8) & 7)) * 0.9) * 0.5 + 0.5
            streak *= math.sin(y * 0.35 + x * 0.05) * 0.5 + 0.5

            base_r = 46.0 + 26.0 * mow
            base_g = 118.0 + 34.0 * mow
            base_b = 44.0 + 20.0 * mow

            shade = grain * 16.0 + streak * 14.0 - 7.0
            r = int(max(0, min(255, base_r + shade * 0.7)))
            g = int(max(0, min(255, base_g + shade)))
            b = int(max(0, min(255, base_b + shade * 0.5)))
            px[x, y] = (r, g, b, 255)

    img.save(path)


# --- the net ----------------------------------------------------------------
#
# The one genuinely see-through thing in the project, and it is a texture
# rather than a shader for a reason with a measurement behind it: a grid drawn
# with a smoothstep in the pixel shader has no mip chain, and a net is the
# worst possible subject for that — a regular pattern seen at a shallow angle
# and minified is exactly what moire is made of. PoC 9 already paid for that
# lesson on a ground texture at 60 -> 30 fps; here it would be a shimmering
# fence as well.
#
# So: white cord, transparent holes, and a box-filtered chain the sampler can
# fall down. What averaging alpha across a mip level gives you is a net that
# fades towards a haze at distance instead of flickering, which is also what a
# real one does.

def write_net(path, size=64, cord=2):
    from PIL import Image

    img = Image.new("RGBA", (size, size), (255, 255, 255, 0))
    px = img.load()
    for y in range(size):
        for x in range(size):
            on = (x % (size // 4)) < cord or (y % (size // 4)) < cord
            if on:
                # Not pure white: cord in shade reads as string, cord at full
                # brightness reads as a wireframe overlay.
                px[x, y] = (226, 230, 234, 235)
    img.save(path)


def main():
    out_dir = sys.argv[1] if len(sys.argv) > 1 else "assets"
    os.makedirs(out_dir, exist_ok=True)

    for name, mesh in (("box", build_box()),
                       ("sphere", build_sphere()),
                       ("wedge", build_wedge())):
        path = os.path.join(out_dir, name + ".obj")
        tris, verts = mesh.write(path)
        print("%s: %d triangles, %d vertices" % (path, tris, verts))

    grass = os.path.join(out_dir, "grass.png")
    write_grass(grass)
    print("%s: 256x256 mown grass, tiling" % grass)

    net = os.path.join(out_dir, "net.png")
    write_net(net)
    print("%s: 64x64 net cord, tiling, alpha" % net)


if __name__ == "__main__":
    main()
