// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Samuele Voltan
//
// GX2 PoC 10 — the asset pipeline: the first geometry in Crema that was not
// generated by code. A baked mesh and a baked texture are loaded from the
// .wuhb content directory and drawn as an instanced squadron.
//
//   - ship.cmesh / hull.ctex come from tools/gen_ship.py + tools/crema_bake.py
//   - the FILE describes the vertex layout: its attribute table is handed
//     straight to the shader compiler, the program hard-codes nothing
//   - loading is pure I/O: no parsing, no byteswapping, no mip generation on
//     the console — the bytes land in GPU memory as they are
//   - free camera on the GamePad, per-pixel lit, fenced pacing, TV + DRC

#include <gx2/draw.h>
#include <gx2/registers.h>
#include <gx2/sampler.h>
#include <gx2/shaders.h>
#include <gx2/state.h>
#include <gx2/texture.h>
#include <whb/gfx.h>
#include <whb/log.h>
#include <vpad/input.h>
#include <coreinit/time.h>
#include <math.h>
#include <string.h>

#include "crema_app.h"
#include "crema_frame.h"
#include "crema_input.h"
#include "crema_matrix.h"
#include "crema_mesh.h"
#include "crema_pak.h"
#include "crema_shader.h"
#include "crema_texture.h"

#define NUM_SHIPS 48

// --- shaders -----------------------------------------------------------------

#define GLOBAL_UBO_DECL \
    "layout(binding = 0) uniform Global {\n" \
    "    mat4 uViewProj;\n" \
    "    vec4 uLightDir;\n"  \
    "    vec4 uCamPos;\n"    \
    "    vec4 uFogParam;\n"  /* x = start, y = end */ \
    "    vec4 uFogColor;\n"  \
    "    vec4 uTime;\n"      \
    "};\n"

static const char *VS_SHIP =
    "#version 450\n"
    "layout(location = 0) in vec3 aPosition;\n"
    "layout(location = 1) in vec3 aNormal;\n"
    "layout(location = 2) in vec2 aUV;\n"
    GLOBAL_UBO_DECL
    "layout(binding = 1) uniform Squadron {\n"
    "    vec4 uShip[96];\n"   // 48 x { position.xyz, phase } + { -, bob, bank, scale }
    "};\n"
    "layout(location = 0) out vec2 vUV;\n"
    "layout(location = 1) out vec3 vNormal;\n"
    "layout(location = 2) out vec3 vWorld;\n"
    "void main()\n"
    "{\n"
    "    vec4 slot = uShip[gl_InstanceID * 2];\n"
    "    vec4 anim = uShip[gl_InstanceID * 2 + 1];\n"
    "    float t = uTime.x + slot.w;\n"
    "    float bank = sin(t * 0.9) * anim.z;\n"
    "    float cb = cos(bank), sb = sin(bank);\n"
    "    vec3 p = vec3(cb * aPosition.x - sb * aPosition.y,\n"
    "                  sb * aPosition.x + cb * aPosition.y, aPosition.z);\n"
    "    vec3 n = vec3(cb * aNormal.x - sb * aNormal.y,\n"
    "                  sb * aNormal.x + cb * aNormal.y, aNormal.z);\n"
    "    vec3 world = p * anim.w + slot.xyz;\n"
    "    world.y += sin(t * 1.3) * anim.y;\n"
    "    gl_Position = uViewProj * vec4(world, 1.0);\n"
    "    vUV = aUV;\n"
    "    vNormal = n;\n"
    "    vWorld = world;\n"
    "}\n";

static const char *PS_SHIP =
    "#version 450\n"
    "layout(location = 0) in vec2 vUV;\n"
    "layout(location = 1) in vec3 vNormal;\n"
    "layout(location = 2) in vec3 vWorld;\n"
    GLOBAL_UBO_DECL
    "layout(binding = 0) uniform sampler2D uHull;\n"
    "layout(location = 0) out vec4 oColor;\n"
    "void main()\n"
    "{\n"
    "    vec3 base = texture(uHull, vUV).rgb;\n"
    "    vec3 n = normalize(vNormal);\n"
    "    float diff = max(dot(n, -uLightDir.xyz), 0.0);\n"
    "    vec3 v = normalize(uCamPos.xyz - vWorld);\n"
    "    vec3 h = normalize(-uLightDir.xyz + v);\n"
    "    float spec = pow(max(dot(n, h), 0.0), 32.0);\n"
    "    vec3 lit = base * (0.22 + 0.78 * diff) + vec3(0.45) * spec;\n"
    "    float dist = length(vWorld - uCamPos.xyz);\n"
    "    float fog = smoothstep(uFogParam.x, uFogParam.y, dist);\n"
    "    oColor = vec4(mix(lit, uFogColor.rgb, fog), 1.0);\n"
    "}\n";

typedef struct {
    Mat4  viewProj;
    float lightDir[4];
    float camPos[4];
    float fogParam[4];
    float fogColor[4];
    float time[4];
} GlobalBlock;

typedef struct {
    const CremaShader *shader;
    const CremaMesh   *mesh;
    const GX2Texture  *tex;
    const GX2Sampler  *sampler;
    uint32_t texUnit;
    int32_t  globalLoc, squadronLoc, globalPsLoc;
    const void *globalUbo;
    const void *squadron;
    size_t   squadronBytes;
} SceneView;

static void drawSquadron(void *user)
{
    const SceneView *s = (const SceneView *)user;

    GX2SetDepthOnlyControl(TRUE, TRUE, GX2_COMPARE_FUNC_LESS);
    GX2SetCullOnlyControl(GX2_FRONT_FACE_CCW, FALSE, TRUE);

    CremaShaderBind(s->shader);
    GX2SetVertexUniformBlock(s->globalLoc, sizeof(GlobalBlock), s->globalUbo);
    GX2SetPixelUniformBlock(s->globalPsLoc, sizeof(GlobalBlock), s->globalUbo);
    GX2SetVertexUniformBlock(s->squadronLoc, s->squadronBytes, s->squadron);
    GX2SetPixelTexture(s->tex, s->texUnit);
    GX2SetPixelSampler(s->sampler, s->texUnit);
    CremaMeshDraw(s->mesh, NUM_SHIPS);
}

int main(int argc, char **argv)
{
    if (!CremaAppInit("poc10-mesh"))
        return -1;
    if (!CremaShaderInitCompiler()) {
        CremaAppShutdown();
        return -1;
    }

    // --- load the baked assets, and time it: nobody has published what the
    // Wii U romfs actually delivers to a homebrew loader ---
    //
    // The same two assets are loaded twice, both ways, in the same run: once as
    // loose files and once out of a .cpak. A benchmark taken on a different day
    // on a different card is not a comparison, and the whole reason the archive
    // exists is a number, so the number is measured here rather than argued.
    CremaMesh ship;
    GX2Texture hull;

    uint64_t loadStart = OSGetSystemTime();
    bool loaded = CremaMeshLoad(&ship, "/vol/content/ship.cmesh") &&
                  CremaTextureLoad(&hull, "/vol/content/hull.ctex");
    double looseMs = (double)OSTicksToMicroseconds(OSGetSystemTime() - loadStart)
                     / 1000.0;
    if (!loaded) {
        WHBLogPrintf("[poc10] asset load failed - is the content dir bundled?");
        CremaShaderShutdownCompiler();
        CremaAppShutdown();
        return -1;
    }
    // thrown away: what we keep is the pair loaded the other way, so that the
    // thing being rendered is the thing that was measured second
    CremaMeshDestroy(&ship);
    CremaTextureDestroy(&hull);

    uint64_t pakStart = OSGetSystemTime();
    CremaPak pak;
    double pakMs = 0.0;
    if (CremaPakOpen(&pak, "/vol/content/assets.cpak")) {
        size_t meshBytes = 0, texBytes = 0;
        const void *meshBlob = CremaPakFind(&pak, "ship.cmesh", &meshBytes);
        const void *texBlob  = CremaPakFind(&pak, "hull.ctex", &texBytes);
        loaded = meshBlob && texBlob &&
                 CremaMeshLoadFromMemory(&ship, meshBlob, meshBytes, "ship.cmesh") &&
                 CremaTextureLoadFromMemory(&hull, texBlob, texBytes, "hull.ctex");
        CremaPakClose(&pak);   // the GPU has its copies now
    } else {
        loaded = false;
    }
    pakMs = (double)OSTicksToMicroseconds(OSGetSystemTime() - pakStart) / 1000.0;
    if (!loaded) {
        WHBLogPrintf("[poc10] .cpak load failed");
        CremaShaderShutdownCompiler();
        CremaAppShutdown();
        return -1;
    }

    WHBLogPrintf("[poc10] LOOSE FILES %.2f ms | ONE .cpak %.2f ms | %+.1f%%",
                 looseMs, pakMs,
                 looseMs > 0.0 ? (pakMs - looseMs) / looseMs * 100.0 : 0.0);

    // the mesh file describes its own vertex layout: hand it to the compiler
    CremaShader *shader = CremaShaderCompile(VS_SHIP, PS_SHIP,
                                             ship.attribs, ship.attribCount);
    if (!shader) {
        CremaMeshDestroy(&ship);
        CremaTextureDestroy(&hull);
        CremaShaderShutdownCompiler();
        CremaAppShutdown();
        return -1;
    }

    int32_t globalLoc   = CremaShaderVSBlockLocation(shader, "Global");
    int32_t squadronLoc = CremaShaderVSBlockLocation(shader, "Squadron");
    int32_t globalPsLoc = CremaShaderPSBlockLocation(shader, "Global");
    if (globalLoc < 0)   globalLoc = 0;
    if (squadronLoc < 0) squadronLoc = 1;
    if (globalPsLoc < 0) globalPsLoc = 0;
    uint32_t texUnit = 0;
    if (shader->ps->samplerVarCount > 0)
        texUnit = shader->ps->samplerVars[0].location;

    GX2Sampler sampler;
    CremaSamplerInitTrilinear(&sampler, GX2_TEX_CLAMP_MODE_WRAP);

    // --- the squadron: a wedge formation, static data written once ---
    float shipData[NUM_SHIPS][8];
    for (int i = 0; i < NUM_SHIPS; i++) {
        int row = 0, seen = 0, col = i;
        while (col > row + 1) {            // rows of 2, 3, 4, ... ships
            col -= row + 2;
            seen += row + 2;
            row++;
        }
        float span = (float)(row + 1);
        shipData[i][0] = ((float)col - span * 0.5f) * 13.0f;  // x
        shipData[i][1] = ((i % 3) - 1) * 2.2f;                // y
        shipData[i][2] = (float)row * -15.0f;                 // z, wedge tip near
        shipData[i][3] = (float)i * 0.61f;                    // animation phase
        shipData[i][4] = 0.0f;
        shipData[i][5] = 0.55f + 0.25f * ((i * 37) % 10) / 10.0f;   // bob
        shipData[i][6] = 0.22f + 0.16f * ((i * 53) % 10) / 10.0f;   // bank
        shipData[i][7] = 1.0f;                                       // scale
        (void)seen;
    }
    uint8_t *squadron = (uint8_t *)CremaUniformAlloc(sizeof(shipData));
    CremaUniformStore(squadron, shipData, sizeof(shipData));

    CremaUniformRing globals;
    CremaUniformRingCreate(&globals, sizeof(GlobalBlock), CREMA_FRAMES_IN_FLIGHT);

    // --- camera ---
    Vec3 camPos = { 0.0f, 5.0f, 30.0f };
    float yaw = 0.0f, pitch = -0.06f;
    Mat4 proj = mat4_perspective(60.0f * 3.14159265f / 180.0f,
                                 16.0f / 9.0f, 0.3f, 400.0f);
    Vec3 lightRaw = { -0.42f, -0.55f, -0.72f };
    Vec3 lightDir = vec3_normalize(lightRaw);

    CremaFrame frame;
    CremaFrameInit(&frame, CREMA_PACING_FENCED, 1);
    WHBLogPrintf("[poc10] %d ships x %u tris = %u tris/frame",
                 NUM_SHIPS, ship.indexCount / 3,
                 NUM_SHIPS * ship.indexCount / 3);
    WHBLogPrintf("[poc10] controls: L-stick move, R-stick look, ZR up, ZL down, B boost");

    SceneView view;
    view.shader        = shader;
    view.mesh          = &ship;
    view.tex           = &hull;
    view.sampler       = &sampler;
    view.texUnit       = texUnit;
    view.globalLoc     = globalLoc;
    view.squadronLoc   = squadronLoc;
    view.globalPsLoc   = globalPsLoc;
    view.squadron      = squadron;
    view.squadronBytes = sizeof(shipData);

    static const float SPACE[4] = { 0.05f, 0.07f, 0.12f, 1.0f };

    CremaFrameStats stats;
    CremaClock clock;
    CremaClockInit(&clock);
    CremaInput input;
    CremaInputInit(&input);

    while (CremaAppRunning()) {
        CremaClockTick(&clock);
        float dt = clock.dt;
        float t = clock.elapsed;

        CremaInputPoll(&input);
        {
            float lx = input.leftX,  ly = input.leftY;
            float rx = input.rightX, ry = input.rightY;

            yaw   -= rx * 1.8f * dt;
            pitch += ry * 1.2f * dt;
            if (pitch >  1.45f) pitch =  1.45f;
            if (pitch < -1.45f) pitch = -1.45f;

            float speed = CremaInputHeld(&input, VPAD_BUTTON_B) ? 40.0f : 12.0f;
            float cp = cosf(pitch), sp = sinf(pitch);
            float cy = cosf(yaw),   sy = sinf(yaw);
            Vec3 fwd   = { -sy * cp, sp, -cy * cp };
            Vec3 right = {  cy, 0.0f, -sy };
            camPos.x += (fwd.x * ly + right.x * lx) * speed * dt;
            camPos.y += (fwd.y * ly + right.y * lx) * speed * dt;
            camPos.z += (fwd.z * ly + right.z * lx) * speed * dt;
            if (CremaInputHeld(&input, VPAD_BUTTON_ZR)) camPos.y += speed * dt;
            if (CremaInputHeld(&input, VPAD_BUTTON_ZL)) camPos.y -= speed * dt;
        }

        uint32_t slot = CremaFrameBegin(&frame);

        Mat4 viewMat = mat4_mul(mat4_rotate_x(-pitch),
                       mat4_mul(mat4_rotate_y(-yaw),
                                mat4_translate(-camPos.x, -camPos.y, -camPos.z)));
        GlobalBlock blk;
        blk.viewProj = mat4_mul(proj, viewMat);
        blk.lightDir[0] = lightDir.x; blk.lightDir[1] = lightDir.y;
        blk.lightDir[2] = lightDir.z; blk.lightDir[3] = 0.0f;
        blk.camPos[0] = camPos.x; blk.camPos[1] = camPos.y;
        blk.camPos[2] = camPos.z; blk.camPos[3] = 0.0f;
        blk.fogParam[0] = 90.0f;  blk.fogParam[1] = 300.0f;
        blk.fogParam[2] = 0.0f;   blk.fogParam[3] = 0.0f;
        blk.fogColor[0] = SPACE[0]; blk.fogColor[1] = SPACE[1];
        blk.fogColor[2] = SPACE[2]; blk.fogColor[3] = 1.0f;
        blk.time[0] = t; blk.time[1] = blk.time[2] = blk.time[3] = 0.0f;
        view.globalUbo = CremaUniformRingStore(&globals, slot, &blk, sizeof(blk));

        CremaFrameDrawBoth(SPACE, drawSquadron, &view);
        CremaFrameEnd(&frame, &stats);
    }

    CremaFrameSettle(&frame);
    CremaUniformRingDestroy(&globals);
    CremaUniformFreeBlock(squadron);
    CremaMeshDestroy(&ship);
    CremaTextureDestroy(&hull);
    CremaShaderFree(shader);
    CremaShaderShutdownCompiler();
    CremaAppShutdown();
    return 0;
}
